### ISSUE TITLE
404 error on similarity.acousticbrainz.org

### ISSUE THREAD

**Issue by petitminion** [metabrainz/troi-recommendation-playground#38]
hello again, 

https://similarity.acousticbrainz.org/api/v1/similarity/tzanetakis/480b391b-827a-4c92-b98f-5b223b74f22c is giving 404 error but https://acousticbrainz.org/480b391b-827a-4c92-b98f-5b223b74f22c exist 

command used : `sudo python3 -m troi.cli playlist ab-similar-recordings -p --debug 480b391b-827a-4c92-b98f-5b223b74f22c tzanetakis`

**Comment by alastair** [comment]
similarity.acousticbrainz.org has a small testing database.
We have released similarity on the main acousticbrainz.org server, so you can use that now. I'm writing some documentation. We will have to update the hostnames in the ab-similar-recordings patch to point to acousticbrainz.org

**Comment by petitminion** [comment]
hostname is in troi-recommendation-playground/troi/acousticbrainz/annoy.py

**Comment by petitminion** [comment]
but I still got 404 with https://acousticbrainz.org/api/v1/similarity/tzanetakis/480b391b-827a-4c92-b98f-5b223b74f22c

**Comment by amCap1712** [comment]
The above PR hopefully fixes the issue. Here's a gist with the debug log of running the command you mentioned with this PR. I am not sure if the PlaylistElement stuff is correct but @alastair will probably know.
https://gist.github.com/amCap1712/c7e68f5ac49d4b958ce3e16b89bc2a3c

**Comment by alastair** [comment]
We decided to remove the endpoint that allows only one MBID and only provide the bulk lookup (to encourage people to look up multiple items at once if they need to).
The endpoint that you need is
> https://acousticbrainz.org/api/v1/similarity/tzanetakis/?recording_ids=480b391b-827a-4c92-b98f-5b223b74f22c

I'll check the PR that @amCap1712 opened and get it merged!

**Comment by alastair** [comment]
This has been merged to main, thanks again for the report!

**Comment by petitminion** [comment]
> This has been merged to main, thanks again for the report!

thx ! 
If you are interested funkwhale collective might use this api :) see https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/1218

**Comment by mayhem** [comment]
Hi! I am quite interested in making recommendations work for Funkwhale -- did we chat in IRC previously or are you a different person? If different, I'd love to chat in IRC sometime....
