### ISSUE TITLE
Keyerror in recommended_recording.py

### ISSUE THREAD

**Issue by ankit2001** [metabrainz/troi-recommendation-playground#7]
While running ./run-docker.sh recommend_recordings.py rob similar command. I am getting this KeyError. Can anyone tell me what is happening.
![Screenshot 2020-08-18 at 11 25 52 PM](https://user-images.githubusercontent.com/44541855/90555242-b1b4cb00-e1b4-11ea-90ba-590ac4c2e0ee.png)

**Comment by mayhem** [comment]
This file no longer exists
